{% set name = "pyoptsparse" %}
{% set version = "2.11.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mdolab/pyoptsparse/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c29d30d97ba2ad5c6d37569c04a1dc39adda697e330cb16c6b25fd94d15fbae3

build:
  number: 1
  skip: true  # [python_impl == 'pypy']
  skip: true  # [win and vc<14]
  skip: true  # [py==38]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
    - python
    - numpy <2.0.0
    - meson >=1.3.2
    - python-build
    - pip
    - swig
    - pkg-config

  host:
    - python
    - numpy
    - ipopt
    - libpgmath                               # [win]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - sqlitedict >=1.6
    - scipy >1.2
    - mdolab-baseclasses >=1.3.1

test:
  imports:
    - pyoptsparse

  source_files:
    - tests

  requires:
    - pip
    - testflo
    - parameterized
    - setuptools

  commands:
    - testflo -n 1 --verbose .
    - pip check

about:
  home: https://mdolab-pyoptsparse.readthedocs-hosted.com/
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Package for formulating and solving nonlinear constrained optimization problems.
  description: |
    pyOptSparse is an object-oriented framework for formulating and solving
    nonlinear constrained optimization problems in an efficient, reusable, and
    portable manner. It is a fork of pyOpt that uses sparse matrices throughout
    the code to more efficiently handle large-scale optimization problems.
    Interfaces are provided for a number of optimizers -- for the conda package the optimizers
    ALPSO, CONMIN, IPOPT, NSGA2, PSQP, and SLSQP are supported.


  doc_url: https://mdolab-pyoptsparse.readthedocs-hosted.com/
  dev_url: https://github.com/mdolab/pyoptsparse

extra:
  recipe-maintainers:
    - ewu63
    - marcomangano
    - eirikurj
    - whophil
